"""sync_model_drift_missing_columns

Revision ID: 3eaf48a79290
Revises: 20260419_onboarding_wizard_state
Create Date: 2026-04-19 20:23:23.060974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3eaf48a79290'
down_revision: Union[str, None] = '20260419_onboarding_wizard_state'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_guests_hotel_id'), 'guests', ['hotel_id'], unique=False)
    op.create_foreign_key(None, 'guests', 'hotel_configuration', ['hotel_id'], ['id'])
    op.add_column('hotel_configuration', sa.Column('owner_email', sa.String(length=200), nullable=True))
    op.add_column('hotel_configuration', sa.Column('subscription_active', sa.Boolean(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('receptionist_view_past_days', sa.Integer(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('receptionist_view_future_days', sa.Integer(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('allow_revenue_manager', sa.Boolean(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('allow_revenue_receptionist', sa.Boolean(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('sync_interval_minutes', sa.Integer(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('safety_buffer_rooms', sa.Integer(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('allow_overbooking', sa.Boolean(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('max_overallocation_pct', sa.Float(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('no_show_cutoff_hours', sa.Integer(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('ota_autopush_enabled', sa.Boolean(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('card_validation_enabled', sa.Boolean(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('payment_retry_attempts', sa.Integer(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('auth_amount_pct', sa.Float(), nullable=False))
    op.add_column('hotel_configuration', sa.Column('stop_sell_channels', sa.Text(), nullable=True))
    op.add_column('hotel_configuration', sa.Column('event_notifications', sa.Text(), nullable=True))
    op.drop_constraint('uq_payment_link_tests_external_reference', 'payment_link_tests', type_='unique')
    op.create_index(op.f('ix_payment_link_tests_external_reference'), 'payment_link_tests', ['external_reference'], unique=True)
    op.drop_index('ix_reservations_hotel_id', table_name='reservations')
    op.create_index('ix_reservation_hotel_id', 'reservations', ['hotel_id'], unique=False)
    op.drop_index('ix_subscriptions_hotel_id', table_name='subscriptions')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_subscriptions_hotel_id', 'subscriptions', ['hotel_id'], unique=False)
    op.drop_index('ix_reservation_hotel_id', table_name='reservations')
    op.create_index('ix_reservations_hotel_id', 'reservations', ['hotel_id'], unique=False)
    op.drop_index(op.f('ix_payment_link_tests_external_reference'), table_name='payment_link_tests')
    op.create_unique_constraint('uq_payment_link_tests_external_reference', 'payment_link_tests', ['external_reference'])
    op.drop_column('hotel_configuration', 'event_notifications')
    op.drop_column('hotel_configuration', 'stop_sell_channels')
    op.drop_column('hotel_configuration', 'auth_amount_pct')
    op.drop_column('hotel_configuration', 'payment_retry_attempts')
    op.drop_column('hotel_configuration', 'card_validation_enabled')
    op.drop_column('hotel_configuration', 'ota_autopush_enabled')
    op.drop_column('hotel_configuration', 'no_show_cutoff_hours')
    op.drop_column('hotel_configuration', 'max_overallocation_pct')
    op.drop_column('hotel_configuration', 'allow_overbooking')
    op.drop_column('hotel_configuration', 'safety_buffer_rooms')
    op.drop_column('hotel_configuration', 'sync_interval_minutes')
    op.drop_column('hotel_configuration', 'allow_revenue_receptionist')
    op.drop_column('hotel_configuration', 'allow_revenue_manager')
    op.drop_column('hotel_configuration', 'receptionist_view_future_days')
    op.drop_column('hotel_configuration', 'receptionist_view_past_days')
    op.drop_column('hotel_configuration', 'subscription_active')
    op.drop_column('hotel_configuration', 'owner_email')
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_index(op.f('ix_guests_hotel_id'), table_name='guests')
    op.drop_column('guests', 'hotel_id')
    # ### end Alembic commands ###
