"""sync_model_drift_missing_columns

Revision ID: 3eaf48a79290
Revises: 20260419_onboarding_wizard_state
Create Date: 2026-04-19 20:23:23.060974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3eaf48a79290'
down_revision: Union[str, None] = '20260419_onboarding_wizard_state'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind is not None else "sqlite"

    if dialect_name == "sqlite":
        with op.batch_alter_table("guests", recreate="always") as batch_op:
            batch_op.add_column(sa.Column("hotel_id", sa.Integer(), nullable=False))
            batch_op.create_foreign_key("fk_guests_hotel_id_hotel_configuration", "hotel_configuration", ["hotel_id"], ["id"])
        op.create_index(op.f("ix_guests_hotel_id"), "guests", ["hotel_id"], unique=False)

        with op.batch_alter_table("hotel_configuration", recreate="always") as batch_op:
            batch_op.add_column(sa.Column("owner_email", sa.String(length=200), nullable=True))
            batch_op.add_column(sa.Column("subscription_active", sa.Boolean(), nullable=False))
            batch_op.add_column(
                sa.Column(
                    "receptionist_view_past_days",
                    sa.Integer(),
                    nullable=False,
                    server_default=sa.text("0"),
                )
            )
            batch_op.add_column(
                sa.Column(
                    "receptionist_view_future_days",
                    sa.Integer(),
                    nullable=False,
                    server_default=sa.text("7"),
                )
            )
            batch_op.add_column(sa.Column("allow_revenue_manager", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("allow_revenue_receptionist", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("sync_interval_minutes", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("safety_buffer_rooms", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("allow_overbooking", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("max_overallocation_pct", sa.Float(), nullable=False))
            batch_op.add_column(sa.Column("no_show_cutoff_hours", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("ota_autopush_enabled", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("card_validation_enabled", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("payment_retry_attempts", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("auth_amount_pct", sa.Float(), nullable=False))
            batch_op.add_column(sa.Column("stop_sell_channels", sa.Text(), nullable=True))
            batch_op.add_column(sa.Column("event_notifications", sa.Text(), nullable=True))
        op.drop_index("ix_reservations_hotel_id", table_name="reservations")
        op.create_index("ix_reservation_hotel_id", "reservations", ["hotel_id"], unique=False)
        op.drop_index("ix_subscriptions_hotel_id", table_name="subscriptions")
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('guests', sa.Column('hotel_id', sa.Integer(), nullable=False))
        op.create_index(op.f('ix_guests_hotel_id'), 'guests', ['hotel_id'], unique=False)
        op.create_foreign_key(
            'fk_guests_hotel_id_hotel_configuration',
            'guests', 'hotel_configuration', ['hotel_id'], ['id'],
        )
        op.add_column('hotel_configuration', sa.Column('owner_email', sa.String(length=200), nullable=True))
        op.add_column('hotel_configuration', sa.Column('subscription_active', sa.Boolean(), nullable=False))
        op.add_column(
            'hotel_configuration',
            sa.Column('receptionist_view_past_days', sa.Integer(), nullable=False, server_default='0'),
        )
        op.add_column(
            'hotel_configuration',
            sa.Column('receptionist_view_future_days', sa.Integer(), nullable=False, server_default='7'),
        )
        op.add_column('hotel_configuration', sa.Column('allow_revenue_manager', sa.Boolean(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('allow_revenue_receptionist', sa.Boolean(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('sync_interval_minutes', sa.Integer(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('safety_buffer_rooms', sa.Integer(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('allow_overbooking', sa.Boolean(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('max_overallocation_pct', sa.Float(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('no_show_cutoff_hours', sa.Integer(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('ota_autopush_enabled', sa.Boolean(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('card_validation_enabled', sa.Boolean(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('payment_retry_attempts', sa.Integer(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('auth_amount_pct', sa.Float(), nullable=False))
        op.add_column('hotel_configuration', sa.Column('stop_sell_channels', sa.Text(), nullable=True))
        op.add_column('hotel_configuration', sa.Column('event_notifications', sa.Text(), nullable=True))
        op.drop_constraint('uq_payment_link_tests_external_reference', 'payment_link_tests', type_='unique')
        op.create_index(op.f('ix_payment_link_tests_external_reference'), 'payment_link_tests', ['external_reference'], unique=True)
        op.drop_index('ix_reservations_hotel_id', table_name='reservations')
        op.create_index('ix_reservation_hotel_id', 'reservations', ['hotel_id'], unique=False)
        op.drop_index('ix_subscriptions_hotel_id', table_name='subscriptions')
        op.drop_constraint('users_email_key', 'users', type_='unique')
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind is not None else "sqlite"

    _hotel_config_cols = [
        'event_notifications', 'stop_sell_channels', 'auth_amount_pct',
        'payment_retry_attempts', 'card_validation_enabled', 'ota_autopush_enabled',
        'no_show_cutoff_hours', 'max_overallocation_pct', 'allow_overbooking',
        'safety_buffer_rooms', 'sync_interval_minutes', 'allow_revenue_receptionist',
        'allow_revenue_manager', 'receptionist_view_future_days',
        'receptionist_view_past_days', 'subscription_active', 'owner_email',
    ]

    if dialect_name == "sqlite":
        # Reverse only what the SQLite upgrade branch did
        op.create_index('ix_subscriptions_hotel_id', 'subscriptions', ['hotel_id'], unique=False)
        op.drop_index('ix_reservation_hotel_id', table_name='reservations')
        op.create_index('ix_reservations_hotel_id', 'reservations', ['hotel_id'], unique=False)
        with op.batch_alter_table('hotel_configuration', recreate='always') as batch_op:
            for col in _hotel_config_cols:
                batch_op.drop_column(col)
        op.drop_index(op.f('ix_guests_hotel_id'), table_name='guests')
        with op.batch_alter_table('guests', recreate='always') as batch_op:
            batch_op.drop_constraint('fk_guests_hotel_id_hotel_configuration', type_='foreignkey')
            batch_op.drop_column('hotel_id')
    else:
        op.drop_index(op.f('ix_users_email'), table_name='users')
        op.create_unique_constraint('users_email_key', 'users', ['email'])
        op.create_index('ix_subscriptions_hotel_id', 'subscriptions', ['hotel_id'], unique=False)
        op.drop_index('ix_reservation_hotel_id', table_name='reservations')
        op.create_index('ix_reservations_hotel_id', 'reservations', ['hotel_id'], unique=False)
        op.drop_index(op.f('ix_payment_link_tests_external_reference'), table_name='payment_link_tests')
        op.create_unique_constraint('uq_payment_link_tests_external_reference', 'payment_link_tests', ['external_reference'])
        for col in _hotel_config_cols:
            op.drop_column('hotel_configuration', col)
        # FK name depends on upgrade vintage: old deploys ran create_foreign_key(None, ...)
        # (PG auto-named it guests_hotel_id_fkey); fresh DBs get the explicit name.
        op.execute('ALTER TABLE guests DROP CONSTRAINT IF EXISTS fk_guests_hotel_id_hotel_configuration')
        op.execute('ALTER TABLE guests DROP CONSTRAINT IF EXISTS guests_hotel_id_fkey')
        op.drop_index(op.f('ix_guests_hotel_id'), table_name='guests')
        op.drop_column('guests', 'hotel_id')
