"""baseline

Revision ID: cb9001557529
Revises: 
Create Date: 2026-03-31 19:04:53.756533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cb9001557529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', name='uq_connection_provider')
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=250), nullable=True),
    sa.Column('address_line2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_configuration',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('deposit_percentage', sa.Float(), nullable=False),
    sa.Column('enable_full_payment', sa.Boolean(), nullable=False),
    sa.Column('enable_deposit_payment', sa.Boolean(), nullable=False),
    sa.Column('enable_cash', sa.Boolean(), nullable=False),
    sa.Column('enable_mercado_pago', sa.Boolean(), nullable=False),
    sa.Column('enable_paypal', sa.Boolean(), nullable=False),
    sa.Column('enable_credit_card', sa.Boolean(), nullable=False),
    sa.Column('enable_debit_card', sa.Boolean(), nullable=False),
    sa.Column('enable_bank_transfer', sa.Boolean(), nullable=False),
    sa.Column('free_cancellation_hours', sa.Integer(), nullable=False),
    sa.Column('cancellation_penalty_percentage', sa.Float(), nullable=False),
    sa.Column('allow_cancellation_after_checkin', sa.Boolean(), nullable=False),
    sa.Column('enable_booking_sync', sa.Boolean(), nullable=False),
    sa.Column('enable_expedia_sync', sa.Boolean(), nullable=False),
    sa.Column('require_document_for_checkin', sa.Boolean(), nullable=False),
    sa.Column('require_terms_acceptance', sa.Boolean(), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('hotel_timezone', sa.String(length=100), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('extra_policies', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_state',
    sa.Column('hotel_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=80), nullable=True),
    sa.Column('owner_role', sa.String(length=120), nullable=True),
    sa.Column('staff_json', sa.Text(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_table('room_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price_per_night', sa.Float(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.CheckConstraint('base_price_per_night > 0', name='ck_category_price_positive'),
    sa.CheckConstraint('max_occupancy > 0', name='ck_category_max_occ_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_pricing',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price_cash', sa.Float(), nullable=True),
    sa.Column('price_transfer', sa.Float(), nullable=True),
    sa.Column('price_mercadopago', sa.Float(), nullable=True),
    sa.Column('price_paypal', sa.Float(), nullable=True),
    sa.Column('price_credit_card', sa.Float(), nullable=True),
    sa.Column('price_debit_card', sa.Float(), nullable=True),
    sa.Column('price_booking', sa.Float(), nullable=True),
    sa.Column('price_expedia', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['room_categories.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('guest_companions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relationship_to_guest', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('available', 'occupied', 'maintenance', 'blocked', 'cleaning', name='room_status_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('floor >= 0', name='ck_room_floor_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['room_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('confirmation_code', sa.String(length=30), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('actual_check_in', sa.DateTime(), nullable=True),
    sa.Column('actual_check_out', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'deposit_paid', 'fully_paid', 'checked_in', 'checked_out', 'cancelled', name='reservation_status_enum', create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('direct', 'booking', 'expedia', 'other_ota', name='reservation_source_enum', create_constraint=True), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('num_adults', sa.Integer(), nullable=False),
    sa.Column('num_children', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_paid >= 0', name='ck_reservation_paid_positive'),
    sa.CheckConstraint('check_out_date > check_in_date', name='ck_reservation_dates'),
    sa.CheckConstraint('num_adults > 0', name='ck_reservation_adults_positive'),
    sa.CheckConstraint('num_children >= 0', name='ck_reservation_children_positive'),
    sa.CheckConstraint('total_amount >= 0', name='ck_reservation_total_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['room_categories.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservation_dates', 'reservations', ['check_in_date', 'check_out_date'], unique=False)
    op.create_index(op.f('ix_reservations_confirmation_code'), 'reservations', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_reservations_external_id'), 'reservations', ['external_id'], unique=False)
    op.create_table('ota_reservation_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('ota_name', sa.String(length=50), nullable=False),
    sa.Column('ota_reservation_id', sa.String(length=100), nullable=False),
    sa.Column('ota_guest_name', sa.String(length=250), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.Enum('pending', 'synced', 'failed', 'conflict', name='ota_sync_status_enum', create_constraint=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_additional_guests',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'guest_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.Enum('deposit', 'full_payment', 'partial_payment', 'balance_payment', 'refund', name='transaction_type_enum', create_constraint=True), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'mercado_pago', 'paypal', 'credit_card', 'debit_card', 'bank_transfer', name='payment_method_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', 'cancelled', name='transaction_status_enum', create_constraint=True), nullable=False),
    sa.Column('external_payment_id', sa.String(length=200), nullable=True),
    sa.Column('external_status', sa.String(length=50), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount != 0', name='ck_transaction_amount_nonzero'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_hotel_id'), 'transactions', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_hotel_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('reservation_additional_guests')
    op.drop_table('ota_reservation_mappings')
    op.drop_index(op.f('ix_reservations_external_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_confirmation_code'), table_name='reservations')
    op.drop_index('ix_reservation_dates', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('rooms')
    op.drop_table('guest_companions')
    op.drop_table('category_pricing')
    op.drop_table('room_categories')
    op.drop_table('onboarding_state')
    op.drop_table('hotel_configuration')
    op.drop_table('guests')
    op.drop_table('connections')
    op.drop_table('users')
    # ### end Alembic commands ###
