"""ota allocation foundation

Revision ID: dee1bd0660f6
Revises: 20260408_payment_link_email_sender_metadata
Create Date: 2026-04-09 15:25:01.903446
"""
from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dee1bd0660f6'
down_revision: Union[str, None] = '20260408_payment_link_email_sender_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _seed_ota_providers() -> None:
    provider_table = sa.table(
        "ota_providers",
        sa.column("code", sa.String(length=50)),
        sa.column("name", sa.String(length=150)),
        sa.column("auth_type", sa.String(length=50)),
        sa.column("security_model", sa.String(length=50)),
        sa.column("api_base_url", sa.String(length=255)),
        sa.column("docs_url", sa.String(length=255)),
        sa.column("supported_features_json", sa.Text()),
        sa.column("requires_certification", sa.Boolean()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime()),
        sa.column("updated_at", sa.DateTime()),
    )
    now = _utcnow()
    op.bulk_insert(
        provider_table,
        [
            {
                "code": "booking",
                "name": "Booking.com",
                "auth_type": "connectivity_api",
                "security_model": "partner_credentials",
                "api_base_url": "https://developers.booking.com/connectivity/docs",
                "docs_url": "https://developers.booking.com/connectivity/docs",
                "supported_features_json": '{"reservations": true, "inventory": true, "pricing": true, "restrictions": true}',
                "requires_certification": True,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "code": "expedia",
                "name": "Expedia Group",
                "auth_type": "rapid_api",
                "security_model": "partner_credentials",
                "api_base_url": "https://developers.expediagroup.com/docs/products/rapid/lodging/",
                "docs_url": "https://developers.expediagroup.com/docs/products/rapid/lodging/",
                "supported_features_json": '{"reservations": true, "inventory": true, "pricing": true, "cancellations": true}',
                "requires_certification": True,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
            {
                "code": "despegar",
                "name": "Despegar",
                "auth_type": "partner_api",
                "security_model": "partner_credentials",
                "api_base_url": "https://api-docs.despegar.com/",
                "docs_url": "https://api-docs.despegar.com/",
                "supported_features_json": '{"reservations": true, "inventory": true, "pricing": true, "after_sales": true}',
                "requires_certification": True,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ota_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('security_model', sa.String(length=50), nullable=False),
    sa.Column('api_base_url', sa.String(length=255), nullable=True),
    sa.Column('docs_url', sa.String(length=255), nullable=True),
    sa.Column('supported_features_json', sa.Text(), nullable=True),
    sa.Column('requires_certification', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_ota_provider_code')
    )
    _seed_ota_providers()
    op.create_table('allocation_policy_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'code', name='uq_allocation_policy_profile_code_hotel')
    )
    op.create_index('ix_allocation_policy_profiles_hotel_id', 'allocation_policy_profiles', ['hotel_id'], unique=False)
    op.create_table('fx_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('preferred_source', sa.String(length=50), nullable=False),
    sa.Column('preferred_side', sa.String(length=20), nullable=False),
    sa.Column('spread_pct', sa.Float(), nullable=False),
    sa.Column('rounding_mode', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'code', name='uq_fx_policy_code_hotel')
    )
    op.create_index('ix_fx_policies_hotel_id', 'fx_policies', ['hotel_id'], unique=False)
    op.create_table('ota_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'HEALTHY', 'DEGRADED', 'ERROR', 'REVOKED', name='ota_connection_status_enum', create_constraint=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_config_encrypted', sa.Text(), nullable=True),
    sa.Column('external_account_id', sa.String(length=120), nullable=True),
    sa.Column('external_property_id', sa.String(length=120), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'environment', name='uq_ota_connection_hotel_provider_env')
    )
    op.create_index('ix_ota_connections_hotel_id', 'ota_connections', ['hotel_id'], unique=False)
    op.create_index('ix_ota_connections_provider_id', 'ota_connections', ['provider_id'], unique=False)
    op.create_table('ota_currency_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rate > 0', name='ck_ota_currency_rates_rate_positive'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ota_currency_rates_hotel_id', 'ota_currency_rates', ['hotel_id'], unique=False)
    op.create_table('tax_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('taxes_included', sa.Boolean(), nullable=False),
    sa.Column('apply_vat_by_default', sa.Boolean(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('foreign_guest_tax_exempt', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'code', name='uq_tax_policy_code_hotel')
    )
    op.create_index('ix_tax_policies_hotel_id', 'tax_policies', ['hotel_id'], unique=False)
    op.create_table('allocation_policy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('constraints_json', sa.Text(), nullable=True),
    sa.Column('weights_json', sa.Text(), nullable=True),
    sa.Column('prompt_summary', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['allocation_policy_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'version_number', name='uq_allocation_policy_version_profile_version')
    )
    op.create_index('ix_allocation_policy_versions_hotel_id', 'allocation_policy_versions', ['hotel_id'], unique=False)
    op.create_table('llm_policy_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', name='llm_policy_suggestion_status_enum', create_constraint=True), nullable=False),
    sa.Column('source_model', sa.String(length=100), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('suggested_policy_json', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['allocation_policy_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_policy_suggestions_hotel_id', 'llm_policy_suggestions', ['hotel_id'], unique=False)
    op.create_index('ix_llm_policy_suggestions_status', 'llm_policy_suggestions', ['status'], unique=False)
    op.create_table('ota_property_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('external_property_id', sa.String(length=120), nullable=False),
    sa.Column('external_property_name', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ota_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'external_property_id', name='uq_ota_property_mapping_hotel_provider_property')
    )
    op.create_index('ix_ota_property_mappings_hotel_id', 'ota_property_mappings', ['hotel_id'], unique=False)
    op.create_table('ota_sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=True),
    sa.Column('scope_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'CANCELLED', name='ota_sync_job_status_enum', create_constraint=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ota_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ota_sync_jobs_hotel_id', 'ota_sync_jobs', ['hotel_id'], unique=False)
    op.create_index('ix_ota_sync_jobs_status', 'ota_sync_jobs', ['status'], unique=False)
    op.create_table('sellable_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('primary_room_category_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('bathroom_type', sa.String(length=40), nullable=True),
    sa.Column('board_type', sa.String(length=40), nullable=True),
    sa.Column('gender_policy', sa.String(length=40), nullable=True),
    sa.Column('accessibility_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_occupancy >= min_occupancy', name='ck_sellable_product_occupancy_range'),
    sa.CheckConstraint('min_occupancy > 0', name='ck_sellable_product_min_occupancy_positive'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_room_category_id'], ['room_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'code', name='uq_sellable_product_code_hotel'),
    sa.UniqueConstraint('hotel_id', 'name', name='uq_sellable_product_name_hotel')
    )
    op.create_index('ix_sellable_products_hotel_id', 'sellable_products', ['hotel_id'], unique=False)
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('tax_policy_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=50), nullable=True),
    sa.Column('guest_scope', sa.String(length=30), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=False),
    sa.Column('tax_name', sa.String(length=150), nullable=False),
    sa.Column('tax_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('applies_when_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_policy_id'], ['tax_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'tax_policy_id', 'tax_code', name='uq_tax_rule_code_hotel_policy')
    )
    op.create_index('ix_tax_rules_hotel_id', 'tax_rules', ['hotel_id'], unique=False)
    op.create_index('ix_tax_rules_tax_policy_id', 'tax_rules', ['tax_policy_id'], unique=False)
    op.create_table('allocation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('horizon_start', sa.DateTime(), nullable=True),
    sa.Column('horizon_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PARTIAL', name='allocation_run_status_enum', create_constraint=True), nullable=False),
    sa.Column('objective_score', sa.Float(), nullable=True),
    sa.Column('solver_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['allocation_policy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allocation_runs_hotel_id', 'allocation_runs', ['hotel_id'], unique=False)
    op.create_index('ix_allocation_runs_status', 'allocation_runs', ['status'], unique=False)
    op.create_table('ota_room_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('sellable_product_id', sa.Integer(), nullable=True),
    sa.Column('room_category_id', sa.Integer(), nullable=True),
    sa.Column('external_room_type_id', sa.String(length=120), nullable=False),
    sa.Column('external_room_type_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ota_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'external_room_type_id', name='uq_ota_room_mapping_hotel_provider_external_room')
    )
    op.create_index('ix_ota_room_mappings_hotel_id', 'ota_room_mappings', ['hotel_id'], unique=False)
    op.create_index('ix_ota_room_mappings_sellable_product_id', 'ota_room_mappings', ['sellable_product_id'], unique=False)
    op.create_table('ota_sync_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('request_payload_encrypted', sa.Text(), nullable=True),
    sa.Column('response_payload_encrypted', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ota_sync_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ota_sync_events_hotel_id', 'ota_sync_events', ['hotel_id'], unique=False)
    op.create_index('ix_ota_sync_events_job_id', 'ota_sync_events', ['job_id'], unique=False)
    op.create_table('product_room_compatibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('sellable_product_id', sa.Integer(), nullable=False),
    sa.Column('room_category_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_kind', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('allows_auto_assignment', sa.Boolean(), nullable=False),
    sa.Column('price_adjustment_type', sa.String(length=30), nullable=True),
    sa.Column('price_adjustment_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'sellable_product_id', 'room_category_id', name='uq_product_room_compatibility_hotel')
    )
    op.create_index('ix_product_room_compatibility_hotel_id', 'product_room_compatibility', ['hotel_id'], unique=False)
    op.create_index('ix_product_room_compatibility_sellable_product_id', 'product_room_compatibility', ['sellable_product_id'], unique=False)
    op.create_table('rate_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('sellable_product_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('pricing_model', sa.String(length=50), nullable=False),
    sa.Column('cancellation_model', sa.String(length=50), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_refundable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_nights_default', sa.Integer(), nullable=False),
    sa.Column('max_nights_default', sa.Integer(), nullable=True),
    sa.Column('free_cancellation_hours', sa.Integer(), nullable=False),
    sa.Column('cancellation_penalty_type', sa.String(length=30), nullable=True),
    sa.Column('cancellation_penalty_value', sa.Float(), nullable=True),
    sa.Column('default_commission_pct', sa.Float(), nullable=True),
    sa.Column('default_markup_pct', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_nights_default IS NULL OR max_nights_default >= min_nights_default', name='ck_rate_plan_max_nights_range'),
    sa.CheckConstraint('min_nights_default > 0', name='ck_rate_plan_min_nights_positive'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'code', name='uq_rate_plan_code_hotel')
    )
    op.create_index('ix_rate_plans_hotel_id', 'rate_plans', ['hotel_id'], unique=False)
    op.create_index('ix_rate_plans_sellable_product_id', 'rate_plans', ['sellable_product_id'], unique=False)
    op.create_table('ota_cancellation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('free_cancel_until_hours', sa.Integer(), nullable=True),
    sa.Column('penalty_type', sa.String(length=30), nullable=True),
    sa.Column('penalty_value', sa.Float(), nullable=True),
    sa.Column('no_show_penalty_type', sa.String(length=30), nullable=True),
    sa.Column('no_show_penalty_value', sa.Float(), nullable=True),
    sa.Column('policy_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'rate_plan_id', name='uq_ota_cancellation_rules_hotel_provider_rate_plan')
    )
    op.create_index('ix_ota_cancellation_rules_hotel_id', 'ota_cancellation_rules', ['hotel_id'], unique=False)
    op.create_table('ota_commission_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=True),
    sa.Column('commission_pct', sa.Float(), nullable=True),
    sa.Column('commission_fixed', sa.Float(), nullable=True),
    sa.Column('payout_model', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name='ck_ota_commission_rules_effective_range'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ota_commission_rules_hotel_id', 'ota_commission_rules', ['hotel_id'], unique=False)
    op.create_table('ota_inventory_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('allotment', sa.Integer(), nullable=True),
    sa.Column('stop_sell', sa.Boolean(), nullable=False),
    sa.Column('closed_to_arrival', sa.Boolean(), nullable=False),
    sa.Column('closed_to_departure', sa.Boolean(), nullable=False),
    sa.Column('min_stay', sa.Integer(), nullable=True),
    sa.Column('max_stay', sa.Integer(), nullable=True),
    sa.Column('advance_purchase_min_days', sa.Integer(), nullable=True),
    sa.Column('advance_purchase_max_days', sa.Integer(), nullable=True),
    sa.Column('release_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('allotment IS NULL OR allotment >= 0', name='ck_ota_inventory_rule_allotment_nonnegative'),
    sa.CheckConstraint('max_stay IS NULL OR min_stay IS NULL OR max_stay >= min_stay', name='ck_ota_inventory_rule_stay_range'),
    sa.CheckConstraint('min_stay IS NULL OR min_stay > 0', name='ck_ota_inventory_rule_min_stay_positive'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'rate_plan_id', 'stay_date', name='uq_ota_inventory_rules_hotel_provider_plan_date')
    )
    op.create_index('ix_ota_inventory_rules_hotel_id', 'ota_inventory_rules', ['hotel_id'], unique=False)
    op.create_table('ota_price_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('commission_pct', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('markup_pct', sa.Float(), nullable=True),
    sa.Column('markup_amount', sa.Float(), nullable=True),
    sa.Column('fx_rate_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('gross_amount >= 0', name='ck_ota_price_rule_gross_nonnegative'),
    sa.CheckConstraint('occupancy IS NULL OR occupancy > 0', name='ck_ota_price_rule_occupancy_positive'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'rate_plan_id', 'stay_date', 'occupancy', name='uq_ota_price_rules_hotel_provider_plan_date_occ')
    )
    op.create_index('ix_ota_price_rules_hotel_id', 'ota_price_rules', ['hotel_id'], unique=False)
    op.create_table('ota_rate_plan_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('external_rate_plan_id', sa.String(length=120), nullable=False),
    sa.Column('external_rate_plan_name', sa.String(length=200), nullable=True),
    sa.Column('pricing_model_external', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ota_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'external_rate_plan_id', name='uq_ota_rate_plan_mapping_hotel_provider_external_plan'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'rate_plan_id', name='uq_ota_rate_plan_mapping_hotel_provider_internal_plan')
    )
    op.create_index('ix_ota_rate_plan_mappings_hotel_id', 'ota_rate_plan_mappings', ['hotel_id'], unique=False)
    op.create_table('rate_plan_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('sales_channel_code', sa.String(length=50), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('base_amount >= 0', name='ck_rate_plan_prices_base_amount_positive'),
    sa.CheckConstraint('occupancy IS NULL OR occupancy > 0', name='ck_rate_plan_prices_occupancy_positive'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_rate_plan_prices_valid_range'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_plan_prices_hotel_id', 'rate_plan_prices', ['hotel_id'], unique=False)
    op.create_index('ix_rate_plan_prices_rate_plan_id', 'rate_plan_prices', ['rate_plan_id'], unique=False)
    op.create_table('solver_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('allocation_run_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=80), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_run_id'], ['allocation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solver_metrics_hotel_id', 'solver_metrics', ['hotel_id'], unique=False)
    op.create_index('ix_solver_metrics_run_id', 'solver_metrics', ['allocation_run_id'], unique=False)
    op.create_table('allocation_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('allocation_run_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('sellable_product_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'APPLIED', 'LOCKED', 'REJECTED', 'MANUAL_REVIEW', name='allocation_assignment_status_enum', create_constraint=True), nullable=False),
    sa.Column('objective_delta', sa.Float(), nullable=True),
    sa.Column('explanation_summary', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_run_id'], ['allocation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_run_id', 'reservation_id', name='uq_allocation_assignment_run_reservation')
    )
    op.create_index('ix_allocation_assignments_hotel_id', 'allocation_assignments', ['hotel_id'], unique=False)
    op.create_index('ix_allocation_assignments_reservation_id', 'allocation_assignments', ['reservation_id'], unique=False)
    op.create_table('allocation_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('allocation_run_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('explanation_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_run_id'], ['allocation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allocation_explanations_hotel_id', 'allocation_explanations', ['hotel_id'], unique=False)
    op.create_index('ix_allocation_explanations_reservation_id', 'allocation_explanations', ['reservation_id'], unique=False)
    op.create_table('manual_override_reasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('override_type', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manual_override_reasons_hotel_id', 'manual_override_reasons', ['hotel_id'], unique=False)
    op.create_index('ix_manual_override_reasons_reservation_id', 'manual_override_reasons', ['reservation_id'], unique=False)
    op.create_table('ota_reservation_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('rate_plan_id', sa.Integer(), nullable=True),
    sa.Column('external_reservation_id', sa.String(length=120), nullable=False),
    sa.Column('external_confirmation_code', sa.String(length=120), nullable=True),
    sa.Column('provider_state', sa.Enum('NEW', 'CONFIRMED', 'MODIFIED', 'CANCEL_REQUESTED', 'CANCELLED', 'HOLD', 'EXPIRED', 'MANUAL_RESOLUTION_REQUIRED', name='ota_reservation_lifecycle_enum', create_constraint=True), nullable=False),
    sa.Column('sync_status', sa.String(length=30), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('gross_total', sa.Float(), nullable=True),
    sa.Column('net_total', sa.Float(), nullable=True),
    sa.Column('commission_total', sa.Float(), nullable=True),
    sa.Column('hold_token', sa.String(length=200), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload_encrypted', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ota_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ota_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'provider_id', 'external_reservation_id', name='uq_ota_reservation_link_hotel_provider_external')
    )
    op.create_index('ix_ota_reservation_links_hotel_id', 'ota_reservation_links', ['hotel_id'], unique=False)
    op.create_index('ix_ota_reservation_links_reservation_id', 'ota_reservation_links', ['reservation_id'], unique=False)
    op.create_table('reservation_allocation_locks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('locked_room_id', sa.Integer(), nullable=True),
    sa.Column('lock_reason_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'is_active', name='uq_reservation_allocation_lock_reservation_active')
    )
    op.create_index('ix_reservation_allocation_locks_hotel_id', 'reservation_allocation_locks', ['hotel_id'], unique=False)
    op.create_table('reservation_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservation_status_history_hotel_id', 'reservation_status_history', ['hotel_id'], unique=False)
    op.create_index('ix_reservation_status_history_reservation_id', 'reservation_status_history', ['reservation_id'], unique=False)
    op.create_table('room_move_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('from_room_id', sa.Integer(), nullable=True),
    sa.Column('to_room_id', sa.Integer(), nullable=True),
    sa.Column('move_type', sa.Enum('AUTO_ASSIGNMENT', 'MANUAL_MOVE', 'UPGRADE', 'DOWNGRADE', 'OVERBOOKING_RESOLUTION', 'MAINTENANCE_RELOCATION', name='room_move_type_enum', create_constraint=True), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('from_room_id IS NOT NULL OR to_room_id IS NOT NULL', name='ck_room_move_events_requires_room'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_move_events_hotel_id', 'room_move_events', ['hotel_id'], unique=False)
    op.create_index('ix_room_move_events_reservation_id', 'room_move_events', ['reservation_id'], unique=False)
    op.create_table('llm_feedback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('allocation_run_id', sa.Integer(), nullable=True),
    sa.Column('manual_override_reason_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('source_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_run_id'], ['allocation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_override_reason_id'], ['manual_override_reasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_feedback_events_hotel_id', 'llm_feedback_events', ['hotel_id'], unique=False)
    op.create_index('ix_llm_feedback_events_reservation_id', 'llm_feedback_events', ['reservation_id'], unique=False)
    op.create_table('reservation_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('resulting_reservation_id', sa.Integer(), nullable=True),
    sa.Column('ota_reservation_link_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('UPGRADE', 'DOWNGRADE', 'DATE_CHANGE', 'OTA_CANCEL_AND_REBOOK', 'MANUAL_RATE_OVERRIDE', 'REFUND', 'OTHER', name='reservation_adjustment_kind_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPLIED', 'FAILED', 'CANCELLED', name='reservation_adjustment_status_enum', create_constraint=True), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('request_source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('amount_delta', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('external_resolution_status', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ota_reservation_link_id'], ['ota_reservation_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservation_adjustments_hotel_id', 'reservation_adjustments', ['hotel_id'], unique=False)
    op.create_index('ix_reservation_adjustments_reservation_id', 'reservation_adjustments', ['reservation_id'], unique=False)
    op.create_table('billing_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('reservation_adjustment_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.Enum('CHARGE', 'CREDIT', 'REFUND', 'COMMISSION', 'TAX_CORRECTION', 'FX_CORRECTION', name='billing_adjustment_type_enum', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('total_amount != 0', name='ck_billing_adjustments_total_nonzero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_adjustment_id'], ['reservation_adjustments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_adjustments_hotel_id', 'billing_adjustments', ['hotel_id'], unique=False)
    op.create_index('ix_billing_adjustments_reservation_id', 'billing_adjustments', ['reservation_id'], unique=False)
    with op.batch_alter_table('reservations', recreate='auto') as batch_op:
        batch_op.add_column(sa.Column('sellable_product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tax_policy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arrival_time_hint', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('subtotal_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('fee_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('commission_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('net_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=False, server_default='ARS'))
        batch_op.add_column(sa.Column('fx_rate_snapshot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source_provider_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_confirmation_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('requested_attributes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pricing_snapshot', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allocation_status', sa.String(length=30), nullable=False, server_default='unassigned'))
        batch_op.add_column(sa.Column('allocation_locked', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('requires_manual_review', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index('ix_reservation_rate_plan_id', ['rate_plan_id'], unique=False)
        batch_op.create_index('ix_reservation_sellable_product_id', ['sellable_product_id'], unique=False)
        batch_op.create_index(op.f('ix_reservations_source_provider_code'), ['source_provider_code'], unique=False)
        batch_op.create_foreign_key(
            'fk_reservations_tax_policy_id_tax_policies',
            'tax_policies',
            ['tax_policy_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_reservations_rate_plan_id_rate_plans',
            'rate_plans',
            ['rate_plan_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_reservations_sellable_product_id_sellable_products',
            'sellable_products',
            ['sellable_product_id'],
            ['id'],
        )
    op.execute(
        """
        UPDATE reservations
        SET
            subtotal_amount = COALESCE(total_amount, 0),
            net_amount = COALESCE(total_amount, 0),
            allocation_status = CASE WHEN room_id IS NULL THEN 'unassigned' ELSE 'assigned' END
        """
    )
    op.add_column('transactions', sa.Column('gross_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('fee_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('net_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('fx_rate_snapshot', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('provider_code', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('pricing_snapshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pricing_snapshot')
    op.drop_column('transactions', 'provider_code')
    op.drop_column('transactions', 'fx_rate_snapshot')
    op.drop_column('transactions', 'net_amount')
    op.drop_column('transactions', 'fee_amount')
    op.drop_column('transactions', 'tax_amount')
    op.drop_column('transactions', 'gross_amount')
    with op.batch_alter_table('reservations', recreate='auto') as batch_op:
        batch_op.drop_constraint('fk_reservations_tax_policy_id_tax_policies', type_='foreignkey')
        batch_op.drop_constraint('fk_reservations_rate_plan_id_rate_plans', type_='foreignkey')
        batch_op.drop_constraint('fk_reservations_sellable_product_id_sellable_products', type_='foreignkey')
        batch_op.drop_index(op.f('ix_reservations_source_provider_code'))
        batch_op.drop_index('ix_reservation_sellable_product_id')
        batch_op.drop_index('ix_reservation_rate_plan_id')
        batch_op.drop_column('requires_manual_review')
        batch_op.drop_column('allocation_locked')
        batch_op.drop_column('allocation_status')
        batch_op.drop_column('pricing_snapshot')
        batch_op.drop_column('requested_attributes_json')
        batch_op.drop_column('external_confirmation_code')
        batch_op.drop_column('source_provider_code')
        batch_op.drop_column('fx_rate_snapshot')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('commission_amount')
        batch_op.drop_column('fee_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal_amount')
        batch_op.drop_column('arrival_time_hint')
        batch_op.drop_column('tax_policy_id')
        batch_op.drop_column('rate_plan_id')
        batch_op.drop_column('sellable_product_id')
    op.drop_index('ix_billing_adjustments_reservation_id', table_name='billing_adjustments')
    op.drop_index('ix_billing_adjustments_hotel_id', table_name='billing_adjustments')
    op.drop_table('billing_adjustments')
    op.drop_index('ix_reservation_adjustments_reservation_id', table_name='reservation_adjustments')
    op.drop_index('ix_reservation_adjustments_hotel_id', table_name='reservation_adjustments')
    op.drop_table('reservation_adjustments')
    op.drop_index('ix_llm_feedback_events_reservation_id', table_name='llm_feedback_events')
    op.drop_index('ix_llm_feedback_events_hotel_id', table_name='llm_feedback_events')
    op.drop_table('llm_feedback_events')
    op.drop_index('ix_room_move_events_reservation_id', table_name='room_move_events')
    op.drop_index('ix_room_move_events_hotel_id', table_name='room_move_events')
    op.drop_table('room_move_events')
    op.drop_index('ix_reservation_status_history_reservation_id', table_name='reservation_status_history')
    op.drop_index('ix_reservation_status_history_hotel_id', table_name='reservation_status_history')
    op.drop_table('reservation_status_history')
    op.drop_index('ix_reservation_allocation_locks_hotel_id', table_name='reservation_allocation_locks')
    op.drop_table('reservation_allocation_locks')
    op.drop_index('ix_ota_reservation_links_reservation_id', table_name='ota_reservation_links')
    op.drop_index('ix_ota_reservation_links_hotel_id', table_name='ota_reservation_links')
    op.drop_table('ota_reservation_links')
    op.drop_index('ix_manual_override_reasons_reservation_id', table_name='manual_override_reasons')
    op.drop_index('ix_manual_override_reasons_hotel_id', table_name='manual_override_reasons')
    op.drop_table('manual_override_reasons')
    op.drop_index('ix_allocation_explanations_reservation_id', table_name='allocation_explanations')
    op.drop_index('ix_allocation_explanations_hotel_id', table_name='allocation_explanations')
    op.drop_table('allocation_explanations')
    op.drop_index('ix_allocation_assignments_reservation_id', table_name='allocation_assignments')
    op.drop_index('ix_allocation_assignments_hotel_id', table_name='allocation_assignments')
    op.drop_table('allocation_assignments')
    op.drop_index('ix_solver_metrics_run_id', table_name='solver_metrics')
    op.drop_index('ix_solver_metrics_hotel_id', table_name='solver_metrics')
    op.drop_table('solver_metrics')
    op.drop_index('ix_rate_plan_prices_rate_plan_id', table_name='rate_plan_prices')
    op.drop_index('ix_rate_plan_prices_hotel_id', table_name='rate_plan_prices')
    op.drop_table('rate_plan_prices')
    op.drop_index('ix_ota_rate_plan_mappings_hotel_id', table_name='ota_rate_plan_mappings')
    op.drop_table('ota_rate_plan_mappings')
    op.drop_index('ix_ota_price_rules_hotel_id', table_name='ota_price_rules')
    op.drop_table('ota_price_rules')
    op.drop_index('ix_ota_inventory_rules_hotel_id', table_name='ota_inventory_rules')
    op.drop_table('ota_inventory_rules')
    op.drop_index('ix_ota_commission_rules_hotel_id', table_name='ota_commission_rules')
    op.drop_table('ota_commission_rules')
    op.drop_index('ix_ota_cancellation_rules_hotel_id', table_name='ota_cancellation_rules')
    op.drop_table('ota_cancellation_rules')
    op.drop_index('ix_rate_plans_sellable_product_id', table_name='rate_plans')
    op.drop_index('ix_rate_plans_hotel_id', table_name='rate_plans')
    op.drop_table('rate_plans')
    op.drop_index('ix_product_room_compatibility_sellable_product_id', table_name='product_room_compatibility')
    op.drop_index('ix_product_room_compatibility_hotel_id', table_name='product_room_compatibility')
    op.drop_table('product_room_compatibility')
    op.drop_index('ix_ota_sync_events_job_id', table_name='ota_sync_events')
    op.drop_index('ix_ota_sync_events_hotel_id', table_name='ota_sync_events')
    op.drop_table('ota_sync_events')
    op.drop_index('ix_ota_room_mappings_sellable_product_id', table_name='ota_room_mappings')
    op.drop_index('ix_ota_room_mappings_hotel_id', table_name='ota_room_mappings')
    op.drop_table('ota_room_mappings')
    op.drop_index('ix_allocation_runs_status', table_name='allocation_runs')
    op.drop_index('ix_allocation_runs_hotel_id', table_name='allocation_runs')
    op.drop_table('allocation_runs')
    op.drop_index('ix_tax_rules_tax_policy_id', table_name='tax_rules')
    op.drop_index('ix_tax_rules_hotel_id', table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index('ix_sellable_products_hotel_id', table_name='sellable_products')
    op.drop_table('sellable_products')
    op.drop_index('ix_ota_sync_jobs_status', table_name='ota_sync_jobs')
    op.drop_index('ix_ota_sync_jobs_hotel_id', table_name='ota_sync_jobs')
    op.drop_table('ota_sync_jobs')
    op.drop_index('ix_ota_property_mappings_hotel_id', table_name='ota_property_mappings')
    op.drop_table('ota_property_mappings')
    op.drop_index('ix_llm_policy_suggestions_status', table_name='llm_policy_suggestions')
    op.drop_index('ix_llm_policy_suggestions_hotel_id', table_name='llm_policy_suggestions')
    op.drop_table('llm_policy_suggestions')
    op.drop_index('ix_allocation_policy_versions_hotel_id', table_name='allocation_policy_versions')
    op.drop_table('allocation_policy_versions')
    op.drop_index('ix_tax_policies_hotel_id', table_name='tax_policies')
    op.drop_table('tax_policies')
    op.drop_index('ix_ota_currency_rates_hotel_id', table_name='ota_currency_rates')
    op.drop_table('ota_currency_rates')
    op.drop_index('ix_ota_connections_provider_id', table_name='ota_connections')
    op.drop_index('ix_ota_connections_hotel_id', table_name='ota_connections')
    op.drop_table('ota_connections')
    op.drop_index('ix_fx_policies_hotel_id', table_name='fx_policies')
    op.drop_table('fx_policies')
    op.drop_index('ix_allocation_policy_profiles_hotel_id', table_name='allocation_policy_profiles')
    op.drop_table('allocation_policy_profiles')
    op.drop_table('ota_providers')
    # ### end Alembic commands ###
