import { useState } from "react";

import { Section, SectionHeading } from "../Section";
import { screenshotFrames } from "../../../content/marketing";

/**
 * Real captures of the running product, generated by e2e/marketing-shots.mjs
 * against the demo hotel from scripts/seed_marketing_demo.py. Nothing here is
 * a mockup, which is the whole point of the section -- the previous version of
 * this page labelled hand-drawn SVGs "screenshots reales".
 *
 * Desktop and phone come from the same run, so the pair is genuinely the same
 * screen at two widths.
 */
export function ProductTourSection() {
  const [activeIndex, setActiveIndex] = useState(0);
  const active = screenshotFrames[activeIndex];

  return (
    <Section id="producto" tone="sunk">
      <SectionHeading
        title="Esto es el sistema, no una maqueta."
        lede="Capturas del producto funcionando, tomadas de un hotel de demostración con la operación cargada."
      />

      <div className="mt-10 flex flex-wrap gap-2">
        {screenshotFrames.map((frame, index) => (
          <button
            key={frame.title}
            type="button"
            aria-pressed={index === activeIndex}
            onClick={() => setActiveIndex(index)}
            className={`min-h-11 rounded-control px-4 text-sm font-medium transition duration-200 ease-rack ${
              index === activeIndex
                ? "bg-ink-950 text-white"
                : "bg-white text-ink-600 ring-1 ring-inset ring-ink-200 hover:text-ink-900"
            }`}
          >
            {frame.title}
          </button>
        ))}
      </div>

      <figure className="mt-6">
        {/* On a phone the desktop capture would land at ~335px wide and be
            unreadable, so the phone capture leads there and the pair only
            appears once there is room for both. */}
        <img
          key={`${active.mobileSrc}-solo`}
          src={active.mobileSrc}
          alt={`${active.title} en el teléfono`}
          width={585}
          height={1266}
          loading="lazy"
          decoding="async"
          className="mx-auto w-full max-w-[280px] rounded-panel border border-ink-200 bg-white shadow-float lg:hidden"
        />

        <div className="hidden gap-5 lg:grid lg:grid-cols-[minmax(0,1fr)_210px] lg:items-end">
          <img
            key={active.src}
            src={active.src}
            alt={`${active.title} en Hotels-PMS`}
            width={2160}
            height={1350}
            loading="lazy"
            decoding="async"
            className="w-full rounded-panel border border-ink-200 bg-white shadow-float"
          />
          <img
            key={active.mobileSrc}
            src={active.mobileSrc}
            alt=""
            width={585}
            height={1266}
            loading="lazy"
            decoding="async"
            className="w-full rounded-panel border border-ink-200 bg-white shadow-float"
          />
        </div>

        <figcaption className="mt-5 max-w-3xl text-base leading-7 text-ink-600">
          {active.description}
        </figcaption>
      </figure>

      <p className="mt-6 max-w-3xl text-sm leading-7 text-ink-500">
        La misma operación entra por el teléfono: es una aplicación web que se instala en el
        dispositivo, para que housekeeping y recepción trabajen desde el pasillo.
      </p>
    </Section>
  );
}

export default ProductTourSection;
